### ISSUE TITLE
Traktor Librarian Issue

### ISSUE THREAD

**Issue by NfoFite** [r0x0r/traktorlibrarian#2]
Used it and found alot of files I knew were on there multiple times, yet when I reopen Traktor there is no collection at all as well as 

Windows 8.1 & Traktor Scratch Pro 2 

Please inform
Thanks
Nate Douglas

**Comment by r0x0r** [comment]
Can you be more specific on the nature of the problem? It does not find duplicates or your collection has disappeared?
